name: Metrics

on:
  schedule:
    # - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  github-stats:
    name: GitHub Stats
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filename: assets/github-stats.svg
          user: Joe-Baqaeen-Insight
          base: header, activity, community, repositories, metadata
          config_timezone: UTC

  github-languages:
    name: Top Languages
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filename: assets/top-languages.svg
          user: Joe-Baqaeen-Insight
          base: ""
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          config_timezone: UTC

  github-achievements:
    name: GitHub Achievements
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filename: assets/achievements.svg
          user: Joe-Baqaeen-Insight
          base: ""
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: X
          config_timezone: UTC
